import type { Metadata } from "next";
import { Noto_Serif_Display, Syne } from "next/font/google";
import "./globals.css";

const bodyFont = Syne({
  variable: "--font-body",
  subsets: ["latin"],
});

const serifFont = Noto_Serif_Display({
  variable: "--font-heading",
  weight: ["300", "400", "500"],
  subsets: ["latin", "greek"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} ${serifFont.variable} h-full min-h-full antialiased`}
      style={{
        backgroundColor: "#FCFCF6",
      }}
    >
      <body className="flex min-h-full flex-col bg-transparent font-sans">{children}</body>
    </html>
  );
}
